### ISSUE TITLE
Phantom stats glitch

### ISSUE THREAD

**Issue by arrnonymous** [ThaumRystra/DiceCloud#155]
When a character without editing permission buffs another character, the character that received the buff permanently gains that buff without ever being able to delete it from their sheet.
![capture](https://user-images.githubusercontent.com/22729309/35379859-abc2e6c6-019e-11e8-99bb-f7df5000070b.JPG)

**Comment by ThaumRystra** [comment]
Interesting. The buff should belong entirely to the character that receives it, so there is no reason a non-editable character should be giving a buff that is any different. Will reproduce and fix.

**Comment by ThaumRystra** [comment]
The root cause of this seems to be players who don't have write access to a character applying buffs to that character.

Rather than solving whatever edge case invalid state that causes, I'd rather just prevent that from happening in the first place, since adding buffs to a character is definitely a "write" style operation, and shouldn't be done by players without write access to a character, as it is definitely an avenue for abuse.

So steps to fix this going forward:

- [ ] clean up all effects in the database whose parent buffs have been deleted
- [ ] ensure a permission check happens when applying buffs, they need to be applied by a player who has write access to that character
