### ISSUE TITLE
Template Items/Spells/Classes/Races

### ISSUE THREAD

**Issue by mcenal** [ThaumRystra/DiceCloud#175]
Be able to create a template and attach to my account. Just like we can add library items to the inventory, I would like to create my own library of Items/Spells/Classes/Races and be able to add them whenever I choose to any character. 

Secondly being able to export/import/share those templates with other people so they can also do the same.

**Comment by ThaumRystra** [comment]
personal libraries are an upcoming feature. They will eventually be extended to races, class levels, and have the ability to share them to other users. Import export won't be implemented, because that is just going to encourage large scale duplication of libraries, and unnecessary load on the database.

**Comment by ThaumRystra** [comment]
#184 has full support for personal templates for absolutely everything, including custom ability scores and attributes
