### ISSUE TITLE
Enhancement : Expanded crit ranges

### ISSUE THREAD

**Issue by MenyeW** [ThaumRystra/DiceCloud#193]
It would be nice if we could have attributes to support certain features like the champion's or hexblade warlock's expanded critical ranges. Even if this were added in manually, it would allow players to remember it on the attack card itself (for example in the features tab).
Basically something that could be used to add more info in the attacks section on the features tab, or could be used specifically to address various types of weapon customization options, that would be a very useful feature

**Comment by MenyeW** [comment]
I tried making this change by pulling and I have it on my local, however I've never done open source work before, could you advise how I could provide it to you for review?

**Comment by ThaumRystra** [comment]
To directly answer your question, you'd make the change in your branch, then create a pull request in GitHub. You can find the docs on how to do that easily enough.

But specifically on your request adding extra attributes isn't something that is going to be merged. I am working on version 2 of DiceCloud, which implements custom attributes for all classes or homebrew content. The main reason extra attributes aren't patched into version 1 is that they require a very large database migration to do, and because of some poor architecture choices, swell the database size and increase hosting costs. In version 2 this isn't an issue anymore.

**Comment by MenyeW** [comment]
That sounds fair, actually. Thanks for your prompt response :) And thank you for such a wonderful service as a whole!

**Comment by ThaumRystra** [comment]
Custom attributes are now a thing in #184, but more  specific implementation will be tracked in #239
