### ISSUE TITLE
API Connectivity Issues

### ISSUE THREAD

**Issue by mommothazaz123** [ThaumRystra/DiceCloud#198]
Opening this issue here so I have a more formal place to point users.
Recently (over the past week or so), Dicecloud has been unexpectedly closing connections to the API (/character/:id/json) without returning any data. I'm not certain if this is specific to a certain IP address or in general.

**Comment by Croebh** [comment]
Its in general, as I was having the same issue on my test version of Avrae.
Unless its something in the Avrae code, but I wouldn't know.

**Comment by Azerix** [comment]
I've only been having this problem for the past two days, but that might just be because I haven't had a reason to add spells until recently.

**Comment by mommothazaz123** [comment]
Any update on this? This is still having a very significant impact.

**Comment by cfi2017** [comment]
The endpoint seems to be working for me, at least.

Is this specific to a given subset of characters? Could you provide an example character id of a character where this issue occurred that hasn't been modified since?

**Comment by mommothazaz123** [comment]
That's the issue; I'm unsure if it's specific to my IP or the endpoint. Other people running local copies of Avrae (@Croebh) have reported the same issue, though. 
As for reproducibility, it's very inconsistent; some characters will work 5 seconds after failing, and some that worked will fail randomly. It doesn't appear to be affecting a specific subset of characters.

**Comment by cfi2017** [comment]
It's definitely not specific to your IP address, that wouldn't make much sense. I can test whether or not the issue persists on a US IP vs, say, a European IP, however I wouldn't get my hopes up. Could you attach the raw response you are getting on an error?

**Comment by cfi2017** [comment]
I've noticed that the response from the server tries to set a cookie called `sc-sticky-session` which is used by the load balancer to route incoming requests to the correct container.

If, say, one of these containers wasn't working properly for some reason that could cause the connection drop. 

If your python script doesn't store the cookie correctly that might be the cause for the randomness in the response failures since the chosen server would be randomly assigned using a round-robin system.

Could you make note of the sticky session cookie on failing responses? This cookie is valid for 24 hours. You could use it to test if subsequent requests using the same cookie also result in errors.

**Comment by mommothazaz123** [comment]
I don't get any response at all on a failing response; Dicecloud just closes the connection before returning anything at all. Let me see what I can do about the cookie; I'll update here in a few hours.

**Comment by mommothazaz123** [comment]
Update 2: Well, it just magically started working again. Alright then.
