### ISSUE TITLE
Automate spell slots based on class

### ISSUE THREAD

**Issue by wickles** [ThaumRystra/DiceCloud#220]
I'm not sure exactly how this would work, or if it's already in there somewhere and I just missed it. But it would be nice if the character system could work out how many spell slots of each level we should have for a given class at a given level. 

For reference this is how I am currently calculating my spell slots, based on the table from the player's manual for my class. Similar formula is repeated 9 times for each spell level of course. Maybe there's a better way to do this already that I'm not noticing? 

![2019-07-11 21_23_10-ShareX-chrome](https://user-images.githubusercontent.com/4229542/61101291-7cbd3d00-a426-11e9-8473-3d9b4f7bcf10.png)

**Comment by Fyresparxx** [comment]
I just got this working with libraries. All characters actually use the multiclassing formulae for spell slots, but when determining caster level, partial casters round UP instead of down if they aren't multiclassed . So I have spell slots as a base stat using casterLevel as a variable, and then a couple of utility stats that calculate that caster level and the number of spellcasting features.
