### ISSUE TITLE
Current HP is altered when leveling up

### ISSUE THREAD

**Issue by toonn** [ThaumRystra/DiceCloud#360]
When leveling up the constitution modifier and the average hit die roll (or the actual rolled hit points when using the Hit Points Roll extension) are added to both the current and maximum HP.

The [PHB states that only the hit point maximum should change](https://rpg.stackexchange.com/a/92777).

I can see a case for keeping the current behavior when a character is at full HP though. Most level ups implicitly come with a long rest so it might be a little surprising having to explicitly long rest to gain your shiny new hit points.

**Comment by ThaumRystra** [comment]
Unfortunately this is an implementation detail that is very baked-in; DiceCloud stores your maximum and damage to that maximum, rather than current value.

While I agree this is technically wrong, rules-as-written, fixing it for level up will break multiple spells on many existing characters with no path for an automated fix.

If your DM insists on following this technically correct ruling, you'll need to manually adjust it at most 19 times over the lifetime of a character, so for now, wont fix.

**Comment by toonn** [comment]
Unfortunate but understandable.

Would it be possible to workaround by adding equivalent HP damage to level ups? In an automatic way of course. I don't mean manually adding the damage.
