### ISSUE TITLE
Color selector always shows red as selected color regardless of actual color selected

### ISSUE THREAD

**Issue by ThaumRystra** [ThaumRystra/DiceCloud#76]
This can probably be fixed by using the [bindProperty API](https://github.com/ThaumRystra/DiceCloud1/blob/master/rpg-docs/client/lib/bindProperty.js), since it was written to help with polymer elements that don't play nicecly with having their properties set by Blaze.

**Comment by Dumbgenius** [comment]
Having messed around with this for a couple of hours, it seems to be caused by a bug in the code of `paper-swatch-picker` itself - even if you go and manually change the `color` attribute of the `paper-swatch-picker` using Inspect Element, the top left swatch is always shown as selected. However, once a color is picked, it stays selected until you close and reopen the dialog.

If you look at the [official demo](https://www.webcomponents.org/element/PolymerElements/paper-swatch-picker/demo/demo/index.html) on webcomponents.org, you'll see the same issue - the top left swatch always appears to be selected when you open the picker itself

**Comment by ThaumRystra** [comment]
Looks like the highlighted color box is based on :focused, rather than selected. So maybe a line to force focus on the selected one on opening.

**Comment by ThaumRystra** [comment]
No longer in #184
